routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomePageController@index')->name('home');
Route::get('aboutus', 'HomePageController@aboutus')->name('aboutus');
Route::get('contactus', 'HomePageController@contactus')->name('contactus');
Route::post('contactus', 'HomePageController@contactusstore')->name('contactus');
Route::get('order-now', 'HomePageController@order_now')->name('order-now');
Route::post('order-now', 'HomePageController@ordernowstore')->name('order-now');
Route::post('filter', 'HomePageController@filter')->name('vehicle.filter');
Route::get('listing', 'HomePageController@listing')->name('listing.index');
Route::get('/car/{vehicle}', 'Admin\DashboardController@car')->name('single.car');
Route::get('/brand/{brand}/model', 'Admin\ModelController@modelOdBrand')->name('brand.model');

Auth::routes();
if (!env('ALLOW_REGISTRATION', false)) {
    Route::any('/register', function () {
        abort(403);
    });
}
Route::middleware(['auth'])->group(function () {
    Route::get('/console', 'Admin\DashboardController@index');
//    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('types', 'Admin\TypeController');

    Route::resource('brands', 'Admin\BrandController');

    Route::resource('models', 'Admin\ModelController');

    Route::resource('vehicles', 'Admin\VehicleController');

    Route::post('vehicles/imagedestroy', 'Admin\VehicleController@imagedestroy');

     Route::resource('users', 'Admin\UserController');

     Route::post('/users/update-pass/{id}','Admin\UserController@updatepass')->name('users.updatepass');

    Route::get('/dashboard', 'Admin\VehicleController@index')->name('dashboard');

});

app/Http/Controllers/Admin/TypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Type;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::all();
        return view('admin.type.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
           
        ]);
        $type = new Type();
        $type->name = $request->name;
        $type->description = $request->description;
        $type->save();
        
    
           return redirect(route('types.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $type = Type::findOrFail($id);

     return view('admin.type.edit', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $validatedData = $request->validate([
            'name' => 'required',
           
        ]);
        
        $type= Type::find($id);
        $type->name=$request->name;
        $type->description=$request->description;
        $type->save();

        return redirect(route('types.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $show = Type::findOrFail($id);
        $show->delete();
        return 'true';
        //return redirect()->route('types.index')
                 //   ->with('success','User deleted successfully');
        // return redirect(route('types.index'));
    }
}

resources/views/admin/type/create.blade.php
@extends('admin.layout.master')
@section('content')
<div class="main-panel">
        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
                Vehicles Types
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Vehicles Types</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Types</li>
                </ol>
            </nav>
          </div>
            <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Vehicles Types</h4>
                  <form class="cmxform"  method="POST" action="{{ route('types.store') }}">
                      @csrf
                    <fieldset>
                      <div class="form-group">
                        <label for="firstname">Name</label>
                        <input id="firstname" class="form-control" name="name" type="text">
                      </div>
                      <div class="form-group">
                        <label for="lastname">Description</label>
                        <textarea id="lastname" rows="5" class="form-control" name="description" type="text"></textarea>
                      </div>
                      
                      <input class="btn btn-primary" type="submit" value="Submit">
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
          </div>
      
</div>
@endsection

resources/views/admin/type/edit.blade.php
@extends('admin.layout.master')
@section('content')
<div class="main-panel">
        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
                Vehicles Types
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Vehicles Types</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Types</li>
                </ol>
            </nav>
          </div>
            <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Vehicles Types</h4>
                  <form class="cmxform"  method="POST" action="{{ route('types.update',$type->id) }}">
                      @csrf
              @method('PATCH')
                    <fieldset>
                      <div class="form-group">
                        <label for="firstname">Name</label>
                        <input id="firstname" class="form-control" value="{{$type->name}}" name="name" type="text">
                      </div>
                      <div class="form-group">
                        <label for="lastname">Description</label>
                        <textarea id="lastname" rows="5" class="form-control" name="description" type="text">{{$type->description}}</textarea>
                      </div>
                      
                      <input class="btn btn-primary" type="submit" value="Submit">
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
          </div>
      
</div>
@endsection

resources/views/admin/type/index.blade.php
@extends('admin.layout.master')
@section('content')
<div class="main-panel">
        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Vehicle Types
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Vehicle Types</a></li>
                <li class="breadcrumb-item active" aria-current="page">Types</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
            
              <h4 class="card-title">Vehicle Types</h4>
                <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>Order #</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($types as $key => $type)
                        <tr>
                           
                            <td>{{++$key}}</td>
                            <td>{{$type->name}}</td>
                            <td>{{$type->description}}</td>
                            
                            <td>
                              <a href="{{route('types.edit',[$type->id])}}"><i class="fas fa-pencil-alt btn-icon-append fa-2x"> </i></a>
                              <a href="" data-id="{{$type->id}}" class="button delete-confirm"><i style="color: #e52d27;" class="remove fa fa-times-circle fa-2x"> </i></a>
                            </td>
                            
                        </tr>
                         @endforeach
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <a href="{{ route('types.create')}}"><div id="settings-trigger"><i class="fas fa-plus-circle fa-10x"></i></div></a>
@endsection

@section('script')
<script src="../../js/data-table.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script type="text/javascript">
  $('.delete-confirm').on('click', function () {
        // return confirm('Are you sure want to delete?');
        event.preventDefault();//this will hold the url
        var id = $(this).data('id');
        Swal.fire({
          title: 'Are you sure?',
          text: "You won't be able to revert this!",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
                if (result.value) {
               $.ajaxSetup({
                        headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
               
               $.ajax({
                type: "delete",
                url: '/types/'+id,
                data: {
                    id: id
                },
                success: function (success) {
                    if (success) {
                        Swal.fire(
                            'Deleted!',
                            'Your record has been deleted.',
                            'success'
                        );
                        location.reload();
                    } else {
                        let msg = result.message;
                        console.log('msg');
                    }
                }
        });
    }
  })
});
</script>
@endsection