routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomePageController@index')->name('home');
Route::get('aboutus', 'HomePageController@aboutus')->name('aboutus');
Route::get('contactus', 'HomePageController@contactus')->name('contactus');
Route::post('contactus', 'HomePageController@contactusstore')->name('contactus');
Route::get('order-now', 'HomePageController@order_now')->name('order-now');
Route::post('order-now', 'HomePageController@ordernowstore')->name('order-now');
Route::post('filter', 'HomePageController@filter')->name('vehicle.filter');
Route::get('listing', 'HomePageController@listing')->name('listing.index');
Route::get('/car/{vehicle}', 'Admin\DashboardController@car')->name('single.car');
Route::get('/brand/{brand}/model', 'Admin\ModelController@modelOdBrand')->name('brand.model');

Auth::routes();
if (!env('ALLOW_REGISTRATION', false)) {
    Route::any('/register', function () {
        abort(403);
    });
}
Route::middleware(['auth'])->group(function () {
    Route::get('/console', 'Admin\DashboardController@index');
//    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('types', 'Admin\TypeController');

    Route::resource('brands', 'Admin\BrandController');

    Route::resource('models', 'Admin\ModelController');

    Route::resource('vehicles', 'Admin\VehicleController');

    Route::post('vehicles/imagedestroy', 'Admin\VehicleController@imagedestroy');

     Route::resource('users', 'Admin\UserController');

     Route::post('/users/update-pass/{id}','Admin\UserController@updatepass')->name('users.updatepass');

    Route::get('/dashboard', 'Admin\VehicleController@index')->name('dashboard');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
           $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
         return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updatepass(Request $request, $id)
    {

        $this->validate($request, [
             'email' => 'required|email|unique:users,email,'.$id,
             'password' => 'same:confirm-password',
        ]);


        $input = $request->all();

        if(!empty($input['password'])){
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = array_except($input,array('password'));
        }


        $user = User::find($id);
        $user->update($input);

          return redirect()->route('users.index')
                        ->with('success','User Password updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layout.master')
@section('content')
<div class="main-panel">
        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
                Users Details
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Users Details</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Users</li>
                </ol>
            </nav>
          </div>
            <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Users Details</h4>
                  @if (count($errors) > 0)
                    <div class="alert alert-danger">
                      <strong>Whoops!</strong> There were some problems with your input.<br><br>
                      <ul>
                         @foreach ($errors->all() as $error)
                           <li>{{ $error }}</li>
                         @endforeach
                      </ul>
                    </div>
                  @endif
                  <form class="cmxform"  method="POST" action="{{ route('users.updatepass',$user->id) }}">
                      @csrf
              @method('post')
                    <fieldset>
                      <div class="form-group">
                        
                        <input id="firstname" class="form-control" value="{{$user->email}}" name="email" type="hidden">
                      </div>
                      <div class="form-group">
                        <label for="firstname">Password</label>
                        <input id="firstname" class="form-control" name="password" type="password">
                      </div>
                       <div class="form-group">
                        <label for="firstname">Confirm Password</label>
                        <input id="firstname" class="form-control"  name="confirm-password" type="password">
                      </div>
                     
                      
                      <input class="btn btn-primary" type="submit" value="Submit">
                    </fieldset>
                  </form>
                </div>
              </div>
            </div>
          </div>
      
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout.master')
@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                    Users 
                </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Users Details</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Details</li>
                    </ol>
                </nav>
            </div>
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Users Details</h4>
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table id="order-listing" class="table">
                                    <thead>
                                    <tr>
                                        <th>Order #</th>
                                        <th>name</th>
                                        <th>email</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($users as $key => $user)
                                        <tr>

                                            <td>{{++$key}}</td>
                                            <td>{{$user->name}}</td>
                                            <td>{{$user->email}}</td>
                                         

                                            <td>
                                                <a href="{{route('users.edit',[$user->id])}}"><i
                                                        class="fas fa fa-key btn-icon-append fa-2x"> </i></a>
                                                
                                            </td>

                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        @endsection

        @section('script')
            <script src="../../js/data-table.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
          
@endsection